// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IChatRepository is an autogenerated mock type for the IChatRepository type
type IChatRepository struct {
	mock.Mock
}

// SendMessage provides a mock function with given fields: query, model, userID, email
func (_m *IChatRepository) SendMessage(query string, model string, userID string, email string) (string, string, error) {
	ret := _m.Called(query, model, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) (string, string, error)); ok {
		return rf(query, model, userID, email)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string) string); ok {
		r0 = rf(query, model, userID, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string) string); ok {
		r1 = rf(query, model, userID, email)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string, string, string) error); ok {
		r2 = rf(query, model, userID, email)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SendMessageStream provides a mock function with given fields: query, model, userID, email, onChunk
func (_m *IChatRepository) SendMessageStream(query string, model string, userID string, email string, onChunk func(string)) (string, string, error) {
	ret := _m.Called(query, model, userID, email, onChunk)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageStream")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, func(string)) (string, string, error)); ok {
		return rf(query, model, userID, email, onChunk)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, func(string)) string); ok {
		r0 = rf(query, model, userID, email, onChunk)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, func(string)) string); ok {
		r1 = rf(query, model, userID, email, onChunk)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string, string, string, func(string)) error); ok {
		r2 = rf(query, model, userID, email, onChunk)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SendMessageStreamRaw provides a mock function with given fields: query, model, userID, email, onRawChunk
func (_m *IChatRepository) SendMessageStreamRaw(query string, model string, userID string, email string, onRawChunk func(map[string]interface{})) (string, string, error) {
	ret := _m.Called(query, model, userID, email, onRawChunk)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageStreamRaw")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, func(map[string]interface{})) (string, string, error)); ok {
		return rf(query, model, userID, email, onRawChunk)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, func(map[string]interface{})) string); ok {
		r0 = rf(query, model, userID, email, onRawChunk)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, func(map[string]interface{})) string); ok {
		r1 = rf(query, model, userID, email, onRawChunk)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string, string, string, func(map[string]interface{})) error); ok {
		r2 = rf(query, model, userID, email, onRawChunk)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SendMessageWithFiles provides a mock function with given fields: query, model, userID, email, files, onChunk
func (_m *IChatRepository) SendMessageWithFiles(query string, model string, userID string, email string, files []map[string]string, onChunk func(string)) (string, string, error) {
	ret := _m.Called(query, model, userID, email, files, onChunk)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageWithFiles")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, []map[string]string, func(string)) (string, string, error)); ok {
		return rf(query, model, userID, email, files, onChunk)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, []map[string]string, func(string)) string); ok {
		r0 = rf(query, model, userID, email, files, onChunk)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, []map[string]string, func(string)) string); ok {
		r1 = rf(query, model, userID, email, files, onChunk)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string, string, string, []map[string]string, func(string)) error); ok {
		r2 = rf(query, model, userID, email, files, onChunk)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SendMessageWithFilesRaw provides a mock function with given fields: query, model, userID, email, files, onRawChunk
func (_m *IChatRepository) SendMessageWithFilesRaw(query string, model string, userID string, email string, files []map[string]string, onRawChunk func(map[string]interface{})) (string, string, error) {
	ret := _m.Called(query, model, userID, email, files, onRawChunk)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageWithFilesRaw")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, []map[string]string, func(map[string]interface{})) (string, string, error)); ok {
		return rf(query, model, userID, email, files, onRawChunk)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, []map[string]string, func(map[string]interface{})) string); ok {
		r0 = rf(query, model, userID, email, files, onRawChunk)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, []map[string]string, func(map[string]interface{})) string); ok {
		r1 = rf(query, model, userID, email, files, onRawChunk)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string, string, string, []map[string]string, func(map[string]interface{})) error); ok {
		r2 = rf(query, model, userID, email, files, onRawChunk)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewIChatRepository creates a new instance of IChatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIChatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IChatRepository {
	mock := &IChatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
