// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IEmailGenerator is an autogenerated mock type for the IEmailGenerator type
type IEmailGenerator struct {
	mock.Mock
}

// Generate provides a mock function with no fields
func (_m *IEmailGenerator) Generate() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewIEmailGenerator creates a new instance of IEmailGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIEmailGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IEmailGenerator {
	mock := &IEmailGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
