// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IFileRepository is an autogenerated mock type for the IFileRepository type
type IFileRepository struct {
	mock.Mock
}

// GetFileURL provides a mock function with given fields: key
func (_m *IFileRepository) GetFileURL(key string) string {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetFileURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// UploadFile provides a mock function with given fields: fileName, fileType, fileData
func (_m *IFileRepository) UploadFile(fileName string, fileType string, fileData []byte) (string, string, error) {
	ret := _m.Called(fileName, fileType, fileData)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, []byte) (string, string, error)); ok {
		return rf(fileName, fileType, fileData)
	}
	if rf, ok := ret.Get(0).(func(string, string, []byte) string); ok {
		r0 = rf(fileName, fileType, fileData)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, []byte) string); ok {
		r1 = rf(fileName, fileType, fileData)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string, []byte) error); ok {
		r2 = rf(fileName, fileType, fileData)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewIFileRepository creates a new instance of IFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IFileRepository {
	mock := &IFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
