// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IIDGenerator is an autogenerated mock type for the IIDGenerator type
type IIDGenerator struct {
	mock.Mock
}

// Generate provides a mock function with no fields
func (_m *IIDGenerator) Generate() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewIIDGenerator creates a new instance of IIDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IIDGenerator {
	mock := &IIDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
